# Generated by Django 3.0.8 on 2020-08-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200714_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='slider')),
            ],
            options={
                'verbose_name': 'Картинка для слайдера',
                'verbose_name_plural': 'Картинки для слайдера',
            },
        ),
    ]
