# Generated by Django 3.0.8 on 2020-08-12 20:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20200813_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 20, 49, 55, 770432, tzinfo=utc), null=True),
        ),
    ]
