# Generated by Django 3.0.8 on 2020-08-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20200813_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.FileField(blank=True, upload_to='file')),
            ],
            options={
                'verbose_name': 'Файл меню',
            },
        ),
    ]
