# Generated by Django 3.0.8 on 2020-08-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20200814_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bacon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='cheese',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='mushrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pepper',
            field=models.BooleanField(default=False),
        ),
    ]
