# Generated by Django 3.0.8 on 2020-08-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_street',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
