# Generated by Django 3.0.8 on 2020-08-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0003_auto_20200806_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Birth_Date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
