# Generated by Django 3.0.8 on 2020-08-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0005_auto_20200806_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address_apartment',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address_entrance',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address_floor',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
