# Generated by Django 3.0.8 on 2020-07-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
