# Generated by Django 3.0.8 on 2020-07-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
