# Generated by Django 3.0.8 on 2020-08-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200731_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_met',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
